[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.140.2"

[build.processing]
# Tell Netlify's scanner that "AUTH0_AUDIENCE" is not a secret
secrets_scan_omit_keys = ["AUTH0_AUDIENCE"]