[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.140.2"


[build.processing]
  secrets_scan_omit_keys = [
    "AUTH0_AUDIENCE",
    "AUTH0_CLIENT_ID",
    "AUTH0_DOMAIN",
    "AUTH0_ISSUER_BASE_URL"
  ]